# Alertmanager configuration for Drone System

global:
  resolve_timeout: 5m

route:
  receiver: 'team-slack'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
- name: 'team-slack'
  slack_configs:
  - channel: '#alerts'
    send_resolved: true
    title: "Drone System Alert"
    text: "Alert: {{ .CommonAnnotations.summary }}
Description: {{ .CommonAnnotations.description }}
Severity: {{ .CommonLabels.severity }}"

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']
